version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "master"
    open-pull-requests-limit: 5
    groups:
      kotlinx:
        patterns:
          - 'org.jetbrains.kotlinx*'
      kotlin-gradle-plugins:
        patterns:
          - 'org.jetbrains.kotlin.android'
          - 'com.google.devtools.ksp'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "master"
    open-pull-requests-limit: 5
