name: Build debug APK

on:
  push:

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload debug APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1