name: Build debug APK

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        version: [full, fdroid]
    name: Build debug APK (${{ matrix.version }})
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build debug APK
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: build${{ matrix.version }}Debug
      - name: Upload debug APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.version }}-debug.apk
          path: app/build/outputs/apk/${{ matrix.version }}/debug/app-${{ matrix.version }}-debug.apk
          retention-days: 1
